/** @type {import('typedoc').TypeDocOptions} */

// https://typedoc.org/options/

module.exports = {
  $schema: 'https://typedoc-plugin-markdown.org/schema.json',
  plugin: ['typedoc-plugin-markdown'],
  tsconfig: 'tsconfig.json',
  excludePrivate: true,
  name: 'Monerium SDK React Provider',
  out: 'docs/generated',
  readme: 'none',
  cleanOutputDir: true,
  searchInComments: true,

  kindSortOrder: [
    'Class',
    'Property',
    'Function',
    'Variable',
    'Interface',
    'TypeAlias',
    'Enum',
    'EnumMember',
    'Document',
  ],
  groupOrder: [
    'Provider',
    'Hooks',
    'Constructors',
    'Properties',
    'Classes',
    'Constants',
    'Functions',
    'Variables',
    'Methods',
    'Utils',
    'Interfaces',
    'Type Aliases',
    'Documents',
    '*',
  ],
  categorizeByGroup: true,
  categoryOrder: [
    'Provider',
    'Constructors',
    'Properties',
    'Classes',
    'Variables',
    'Functions',
    'Methods',
    'Interfaces',
    'Type Aliases',
    'Hooks',
    'Documents',
    '*',
    'Other',
  ],
  entryPoints: ['src/index.ts'],
  sortEntryPoints: true,
  entryPointStrategy: 'Resolve',
  expandObjects: true,
  hideParameterTypesInTitle: true,
  expandParameters: true,

  // indexFormat: 'table',
  parametersFormat: 'table',
  typeDeclarationFormat: 'table',
  interfacePropertiesFormat: 'table',
  classPropertiesFormat: 'table',
  enumMembersFormat: 'table',
  propertyMembersFormat: 'table',

  hidePageHeader: true,

  compilerOptions: {
    noEmit: true,
  },
};
