const chains = [
  {
    chainId: 1,
    name: 'Ethereum',
    explorerUrl: 'https://etherscan.io/token/',
    explorerName: 'Etherscan',
    logo: 'https://monerium.app/assets/chains/ethereum.svg',
    color: '#E6EEF7',
  },
  {
    chainId: 11155111,
    name: 'Sepolia',
    explorerUrl: 'https://sepolia.etherscan.io/token/',
    explorerName: 'Etherscan',
    logo: 'https://monerium.app/assets/chains/ethereum.svg',
    color: '#E6EEF7',
    testnet: true,
  },

  {
    chainId: 100,
    name: 'Gnosis',
    explorerUrl: 'https://gnosisscan.io/token/',
    explorerName: 'Gnosisscan',
    logo: 'https://monerium.app/assets/chains/gnosis.svg',
    color: '#E5EAE7',
  },
  {
    chainId: 10200,
    name: 'Chiado',
    explorerUrl: 'https://blockscout.chiadochain.net/address/',
    explorerName: 'Blockscout',
    logo: 'https://monerium.app/assets/chains/gnosis.svg',
    color: '#E5EAE7',
    testnet: true,
  },

  {
    chainId: 137,
    name: 'Polygon',
    explorerUrl: 'https://polygonscan.com/token/',
    explorerName: 'Polyscan',
    logo: 'https://monerium.app/assets/chains/polygon.svg',
    color: '#ECE6F7',
  },
  {
    chainId: 80002,
    name: 'Amoy',
    explorerUrl: 'https://amoy.polygonscan.com/token/',
    explorerName: 'Polyscan',
    logo: 'https://monerium.app/assets/chains/polygon.svg',
    color: '#ECE6F7',
    testnet: true,
  },
  {
    chainId: 42161,
    name: 'Arbitrum',
    explorerUrl: 'https://arbiscan.io/token/',
    explorerName: 'Arbiscan',
    logo: 'https://monerium.app/assets/chains/arbitrum.svg',
    color: '#BCCCFF',
  },
  {
    chainId: 421614,
    name: 'Arbitrum Sepolia',
    explorerUrl: 'https://sepolia.arbiscan.io/token/',
    explorerName: 'Arbiscan',
    logo: 'https://monerium.app/assets/chains/arbitrum.svg',
    color: '#BCCCFF',
    testnet: true,
  },
  {
    chainId: 59144,
    name: 'Linea',
    explorerUrl: 'https://lineascan.build/token/',
    explorerName: 'Lineascan',
    logo: 'https://monerium.app/assets/chains/linea.svg',
    color: '#e1f1f5',
  },
  {
    chainId: 59141,
    name: 'Linea Sepolia',
    explorerUrl: 'https://sepolia.lineascan.build/token/',
    explorerName: 'Lineascan',
    logo: 'https://monerium.app/assets/chains/linea.svg',
    color: '#e1f1f5',
    testnet: true,
  },
  {
    chainId: 534352,
    name: 'Scroll',
    explorerUrl: 'https://scrollscan.com/token/',
    explorerName: 'ScrollScan',
    logo: 'https://monerium.app/assets/chains/scroll.svg',
    color: '#f5ebe1',
  },
  {
    chainId: 534351,
    name: 'Scroll Sepolia',
    explorerUrl: 'https://sepolia.scrollscan.com/token/',
    explorerName: 'ScrollScan',
    logo: 'https://monerium.app/assets/chains/scroll.svg',
    color: '#f5ebe1',
    testnet: true,
  },
  {
    chainId: 8453,
    name: 'Base',
    explorerUrl: 'https://basescan.org/token/',
    explorerName: 'BaseScan',
    logo: 'https://monerium.app/assets/chains/base.svg',
    color: '#d6e7ff',
  },
  {
    chainId: 84532,
    name: 'Base Sepolia',
    explorerUrl: 'https://sepolia.basescan.org/token/',
    explorerName: 'BaseScan',
    logo: 'https://monerium.app/assets/chains/base.svg',
    color: '#d6e7ff',
    testnet: true,
  },
];

export default chains;
