import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    // { type: 'autogenerated', dirName: '.' },
    {
      id: 'index',
      type: 'doc',
      label: 'Welcome',
      // items: ['index'],
    },
    {
      type: 'link',
      label: 'API Documentation',
      href: '/docs/api',
    },
    // {
    //   type: 'autogenerated',
    //   dirName: 'packages',
    // }
    {
      type: 'category',
      label: 'Packages',
      items: [
        { type: 'doc', id: 'packages/SDK/index' },
        { type: 'doc', id: 'packages/SDK React Provider/index' },
      ],
    },
  ],
  // customSidebar: [
  //   {
  //     type: 'link',
  //     label: 'Welcome',
  //     href: '/docs/openapi',
  //   },
  // ],
};

export default sidebars;
