import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
  typedocSidebar: [
    {
      type: 'category',
      label: 'Welcome',
      link: {
        type: 'doc',
        id: 'index',
      },
      items: ['index'],
    },
    {
      type: 'category',
      label: 'SDK',
      link: {
        type: 'doc',
        id: 'packages/sdk/index',
      },
      items: require('./docs/packages/sdk/typedoc-sidebar.cjs'),
    },
    {
      type: 'category',
      label: 'SDK React Provider',
      link: {
        type: 'doc',
        id: 'packages/sdk-react-provider/index',
      },
      items: require('./docs/packages/sdk-react-provider/typedoc-sidebar.cjs'),
    },
  ],
};

export default sidebars;
