name: NPM

on:
  push:

jobs:
  echo-stuff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Cache PNPM install and Turbo
        uses: ./.github/actions/cache-setup
      - name: Build
        run: pnpm build

      - name: Echo pnpm config list
        run: pnpm config list
      - name: Echo hashed NPM_TOKEN
        run: echo "${{ secrets.NPM_TOKEN }}" | sha256sum
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - name: Publish React Provider
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        # run: pnpm --filter @monerium/sdk-react-provider pub:pre
        run: pnpm publish --filter @monerium/sdk-react-provider --access public --no-git-checks
