name: NPM

on:
  push:

jobs:
  echo-stuff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
      - name: Echo pnpm config list
        run: pnpm config list
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
