name: New Task Workflow

on:
  workflow_run:
    workflows: ["Cache and Install Dependencies"]
    types:
      - completed

jobs:
  new-task:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
        #   version: 9.2.0
        #   run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
        #   cache: "pnpm"

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        name: Restore pnpm cache
        with:
          path: .pnpm-store
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install
