name: Cache and Install Dependencies

on:
  pull_request:
    branches:
      - main

jobs:
  cache-and-install:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      - name: Setup
        uses: ./.github/actions/cache-setup.yml
      - name: TurboBuild
        run: pnpm build
      # uses: ./.github/actions/cache-pnpm
  build:
    uses: ./.github/workflows/build.yml
